# Generated by Django 2.1.7 on 2019-04-07 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.TextField(unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
