# Generated by Django 2.1.7 on 2019-04-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_bot', '0004_auto_20190418_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='author_name',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='authors',
            field=models.ManyToManyField(to='news_bot.Author'),
        ),
    ]
