# Generated by Django 2.1.7 on 2019-05-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_bot', '0005_auto_20190418_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_email',
        ),
        migrations.AddField(
            model_name='authoremail',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_bot.Author'),
        ),
    ]
