# Generated by Django 2.1.7 on 2019-05-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_bot', '0006_auto_20190502_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='news_bot.Author'),
        ),
    ]
